### PR TITLE
-Implemented List and Add methods for Push Service

### PR DESCRIPTION
**Pull request by atmishra**
#9 -
- Added Push resource
- Created Push service with add and list method implemented.
- Created test cases for list method

### CODE REVIEW

**Comment by atmishra** [comment]
@indradhanush  Can you please help me. How should I go about resolving these issues?

**Comment by indradhanush** [comment]
@atmishra Thanks for the PR!

I looked at the failure output of the build and it looks like travis is unable to obtain an access token and account id from the environment settings for your PR. I'm not sure what is the reason behind that. However I pushed your branch to my repo and the tests seem to be running, although the one that you added in this PR still fails.

Could you do the following:
1. Sign up on Travis
2. Import your fork of this repo into travis so that travis can run build for your branches
3. Add your api key and account id as environment variables under the settings for this repo on Travis. This same as the environment variables required for local development. This is explained here: [CONTRIBUTING.md](https://github.com/indradhanush/dnsimple2-python/blob/master)/CONTRIBUTING.md

I'm hoping once you've done this, build should run normally for your branches under your travis account. I'll investigate why your PR is unable to fetch the environment variables separately.

I hope this helps.

**Comment by atmishra** [comment]
Hey @indradhanush, I have setup my travis account and tried to build my feat/push-client branch. But the build is failing for all the python3.x environment. The builds are failing at line 460 in test_domains.py and line 468 in test_whoami.py

**Comment by indradhanush** [comment]
@atmishra Sorry for the late response. 

There was a bug in the travis ci configuration that skipped all tests for python 2.x thus giving the false impression that they fail only for 3.x ; Commit c274159f02521ef619f06e4fed5e3d8353ff29e0 fixes this and I've pushed it to master. Could you please pull in the latest changes and try again?

Regarding the failure in the `WhoAmIServiceTests.test_get` I don't see why they should fail for your code unless you've not set the environment variables on travis correctly. Could you cross check if you've set the following variables on travis as well:
   - `DNSIMPLE_ACCOUNT_ID`
   - `DNSIMPLE_V2_ACCESS_TOKEN`

Also, I realized later that concurrent builds cause abrupt failures and disabling them helps prevent that. I've added notes on that here: 37460599c6f801ef13f8a3ed267619401d73a010

**Comment by indradhanush** [comment]
Also I pulled your branch and built it [here](https://travis-ci.org/indradhanush/dnsimple2-python/builds/297289292) and the test `PushServiceTests.test_list_push_for_invalid_account` fails.

**Comment by indradhanush** [comment]
I will go ahead and close this. Feel free to reopen if you get around to fixing the tests. :slightly_smiling_face:

**Pull request closed without merging**
